### Get all transactions
GET http://localhost:3000/api/transactions


### Get transaction
GET http://localhost:3000/api/transactions/000


### Add new transaction
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "type": "income",
  "amount": 1500,
  "category": "Salary",
  "account": "bank",
  "description": "salary june 2025"
}


### Update a transaction
PUT http://localhost:3000/api/transactions/688500bcd52340fc23d89239
Content-Type: application/json

{
  "type": "expense",
  "amount": 200,
  "category": "Groceries",
  "account": "savings",
  "description": "dinner"
}


### Delete a transaction
DELETE http://localhost:3000/api/transactions/6884fdf9ff97296a13495a21


### Get all categories
GET http://localhost:3000/api/categories


### Get category
GET http://localhost:3000/api/categories/6885003dd52340fc23d89230


### Create category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "type": "income",
  "name": "Salary"
}


### Update a category
PUT http://localhost:3000/api/categories/6885003dd52340fc23d89230
Content-Type: application/json

{
  "type": "expense",
  "name": "funding"
}


### Delete a category
DELETE http://localhost:3000/api/categories/6885003dd52340fc23d89230